# Generated by Django 3.2.12 on 2024-04-02 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('photo_url', models.URLField()),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='createdTime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='painter',
            old_name='AboutPainter',
            new_name='about_painter',
        ),
        migrations.RenameField(
            model_name='painter',
            old_name='createdTime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='painter',
            old_name='photoUrl',
            new_name='photo_url',
        ),
        migrations.RenameField(
            model_name='painter',
            old_name='workExperience',
            new_name='work_experience',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
