# Generated by Django 3.2.12 on 2024-04-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240407_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paint',
            name='image_path',
        ),
        migrations.AddField(
            model_name='paint',
            name='image',
            field=models.ImageField(default='exit', upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
