# Generated by Django 3.2.12 on 2024-04-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240407_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='image',
            field=models.ImageField(upload_to='add/pictures/'),
        ),
    ]
