# Generated by Django 3.2.12 on 2024-04-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20240409_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='about_paint',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
