# Generated by Django 3.2.12 on 2024-05-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20240506_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='my_orders',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(default='exit', verbose_name=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painter',
            name='orders',
            field=models.JSONField(default=list),
        ),
    ]
